# Generated by Django 3.2.16 on 2024-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_follow_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user', 'following'),
                name='unique_follow_subscriber_pair',
            ),
        ),
    ]
