# Generated by Django 3.2.16 on 2024-02-10 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0011_alter_follow_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_subscriber_pair',
        ),
    ]
