# Generated by Django 3.2.16 on 2024-02-11 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0013_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',)},
        ),
    ]
