# Generated by Django 3.2.16 on 2024-02-11 20:26

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0015_follow_unique_user_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('user', django.db.models.expressions.F('following')),
                    _negated=True,
                ),
                name='cannot_follow_oneself',
            ),
        ),
    ]
